spring:
  application:
    name: money-transfer-service
  
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=MoneyTransferDB;encrypt=true;trustServerCertificate=true
    username: sa
    password: YourStrong@Passw0rd
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
  
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
    cache:
      type: redis
      redis:
        time-to-live: 60000
  
  jms:
    template:
      default-destination: TRANSFER.COMPLETED
  
  mvc:
    problem-details:
      enabled: false

ibm:
  mq:
    conn-name: localhost(1414)
    queue-manager: QM1
    channel: DEV.APP.SVRCONN
    ssl:
      enabled: false
        
server:
  port: 8081
  servlet:
    context-path: /api/v1
  error:
    include-message: always
    include-binding-errors: always
  
logging:
  level:
    com.assignment.money_transfer_service: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: DEBUG
    org.springframework.validation: DEBUG
